server {
    # Cloud Run expects the container to listen on port 8080
    listen 8080;
    server_name _;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # This ensures that if you ever use React Router, refreshing the page doesn't break
        try_files $uri $uri/ /index.html;
    }
}
