server {
  # Cloud Run provides the PORT env var, Nginx should listen on it.
  listen 8080;

  # Set the root for requests
  root /usr/share/nginx/html;
  index index.html;

  location / {
    # First attempt to serve request as file, then
    # as directory, then fall back to displaying a 404.
    try_files $uri /index.html;
  }
}
